### ISSUE TITLE
<h1>-<h4>标题似乎有点浅

### ISSUE THREAD

**Issue by linesh-simplicity** [sofish/typo.css#57]
正在看typo.css这个仓库首页，觉得想法非常赞，也确实有这样需求，毕竟排版不好非常令人捉急。不过这里发现`<h1>`到`<h4>`标题的字体比较细，从样式上讲可能有这样设计的考虑，而从内容上讲则觉得标题hold不住下面的内容。非设计专业，只是浅见，有错漏之处也请给我提出。

![image](https://cloud.githubusercontent.com/assets/11895199/16642375/ef913478-443c-11e6-833a-484ef6903714.png)
这是现在官网的样式。标题比较细，视觉效果比较素雅，不过反倒使得在内容中辨别标题变得困难。

![image](https://cloud.githubusercontent.com/assets/11895199/16642383/03ac640a-443d-11e6-977f-eba9bb99bb4d.png)
以上的话，标题何在，段落与段落之间到何处，则内容上更一目了然。不一定需要选这个字体，我想建议的点在于，**可以通过适当增加标题的weight来使其能在正文内容中被迅速标识出来**。欢迎讨论。

**Comment by sofish** [comment]
确实是设计需要，如果觉得想要重一点，可以把 `h1, h2, h3, h4, h5, h6 {font-weight: 900;}` 重置掉这一行 https://github.com/sofish/typo.css/blob/master/typo.css#L244
